apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: u614iah1d-nodejs 
  janus-idp.io/tekton: u614iah1d-nodejs
  backstage.io/kubernetes-id: u614iah1d-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u614iah1d-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  