apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: u614iah1d-nodejs-gitops
  description: This is GitOps manifest for u614iah1d-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: u614iah1d-nodejs
    janus-idp.io/tekton: u614iah1d-nodejs 
    backstage.io/kubernetes-id: u614iah1d-nodejs 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:u614iah1d-nodejs
